services:
  - type: web
    name: youtube-audio-downloader
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DOWNLOADS_DIR
        value: /tmp/downloads
    healthCheckPath: /
    autoDeploy: true
    plan: free 